---
######################
######################
## GitHub CI Action ##
######################
######################
name: CI

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

##############################
# Start the job on all pulls #
##############################
on:
  push:
  pull_request:
    branches: [main]

###################
# Set Global Envs #
###################
env:
  node_version: '14'

############
# Set Jobs #
############
jobs:
  tests:
    # Name the Job
    name: CI
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:
      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      #################
      # Setup Node JS #
      #################
      - name: Setup Node JS
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@qbcart'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.QBC_GITHUB_PACKAGES }}

      ################
      # Install Deps #
      ################
      - name: Install Deps
        shell: bash
        run: npm install

      #################
      # Build Project #
      #################
      - name: Build Project
        shell: bash
        run: npm run build

      #############
      # Lint Code #
      #############
      - name: Lint Code
        shell: bash
        run: npm run lint

      #############
      # Run Tests #
      #############
      - name: Run Tests
        shell: bash
        run: |
          npm run test:ci
